name: Commit Message Check

on:
  workflow_call:
    inputs:
      bypassCommitCheck:
        description: 'Set to true to bypass the commit message check.'
        required: false
        type: boolean

jobs:
  check_commit_message:
    runs-on: ubuntu-latest
    if: ${{ inputs.bypassCommitCheck != 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Commit Message
        shell: bash
        run: |
          # Retrieve the commit messages
          COMMIT_MSGS=$(git log -n 10 --pretty=format:"%s" HEAD^..HEAD)
          
          # Define a regular expression to match the conventional commit pattern
          CONVENTIONAL_REGEX="^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert|wip)(\(.+\))?:\s.+"
          
          # Loop through each commit message and check against the conventional pattern
          for COMMIT_MSG in $COMMIT_MSGS; do
            if [[ ! $COMMIT_MSG =~ $CONVENTIONAL_REGEX ]]; then
              echo "::error::Commit message '$COMMIT_MSG' does not follow the Conventional Commits format. Please use a message like 'feat: add new feature' or 'fix(scope): correct issue'."
              exit 1
            else
              echo "Commit message '$COMMIT_MSG' is valid."
            fi
          done