name: Essentials Plugin Build 3-Series

on:
  workflow_call:
    inputs:
      newVersion:
        description: 'new version?'
        required: true
        type: string
      version:
        description: 'The version of the file to build and push'
        required: true
        type: string
      tag:
        description: 'The tag of the image to build and push'
        required: true
        type: string
      channel:
        description: 'The channel of the image to build and push'
        required: true
        type: string 
permissions:
  contents: write
  packages: write
jobs:
  Build_Project_3-Series:
    runs-on: windows-2019
    env:
      VERSION: ${{ inputs.version }}
      BUILD_TYPE: ${{ inputs.channel == '' && 'Release' || 'Debug' }}
      NUSPEC_FILE: ''
    steps:
      # First we checkout the source repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Fetch all tags
      - name: Fetch tags
        run: git fetch --tags
      # Generate the appropriate version number
      # - name: Set Version Number
      #   shell: powershell
      #   run: |
      #     $version = ./.github/scripts/GenerateVersionNumber.ps1
      #     echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      # Use the version number to set the version of the assemblies
      - name: Update AssemblyInfo.cs
        shell: powershell
        run: |
          function Update-SourceVersion {
          Param ([string]$Version)
          #$fullVersion = $Version
          $baseVersion = [regex]::Match($Version, "(\d+.\d+.\d+).*").captures.groups[1].value
          $NewAssemblyVersion = 'AssemblyVersion("' + $baseVersion + '.*")'
          Write-Output "AssemblyVersion = $NewAssemblyVersion"
          $NewAssemblyInformationalVersion = 'AssemblyInformationalVersion("' + $Version + '")'
          Write-Output "AssemblyInformationalVersion = $NewAssemblyInformationalVersion"
          foreach ($o in $input) {
              Write-output $o.FullName
              $TmpFile = $o.FullName + ".tmp"
              get-content $o.FullName |
              ForEach-Object {
                  $_ -replace 'AssemblyVersion\(".*"\)', $NewAssemblyVersion } |
              ForEach-Object {
                  $_ -replace 'AssemblyInformationalVersion\(".*"\)', $NewAssemblyInformationalVersion
              }  > $TmpFile 
              move-item $TmpFile $o.FullName -force
            }
          }
          function Update-AllAssemblyInfoFiles ( $version ) {
              foreach ($file in "AssemblyInfo.cs", "AssemblyInfo.vb" ) {
                  get-childitem -Path $Env:GITHUB_WORKSPACE -recurse | Where-Object { $_.Name -eq $file } | Update-SourceVersion $version ;
              }
          }
          # validate arguments
          $r = [System.Text.RegularExpressions.Regex]::Match($Env:VERSION, "\d+\.\d+\.\d+.*");
          if ($r.Success) {
              Write-Output "Updating Assembly Version to $Env:VERSION ...";
              Update-AllAssemblyInfoFiles $Env:VERSION;
          }
          else {
              Write-Output " ";
              Write-Output "Error: Input version $Env:VERSION does not match x.y.z format!"
              Write-Output " ";
              Write-Output "Unable to apply version to AssemblyInfo.cs files";
          }
      - name: restore Nuget Packages
        run: nuget install .\packages.config -OutputDirectory .\packages -ExcludeVersion
      # Login to Docker
      - name: Login to Docker
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      # Build the solutions in the docker image
      - name: Get SLN Path 
        shell: powershell
        run: |
          $solution_path = Get-ChildItem *.3Series.sln -recurse 
          $solution_path = $solution_path.FullName
          $solution_path = $solution_path -replace "(?:[^\\]*\\){4}", ""
          Write-Output $solution_path
          echo "SOLUTION_PATH=$($solution_path)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        
        # Set the SOLUTION_FILE
      - name: Get SLN File 
        shell: powershell
        run: |
          $solution_file = Get-ChildItem .\*.3Series.sln -recurse -Path "$($Env:GITHUB_WORKSPACE)" 
          echo "SOLUTION_FILE=$($solution_file.BaseName)"| Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        
      - name: Build Solution
        shell: powershell
        run: |
          Invoke-Expression "docker run --rm --mount type=bind,source=""$($Env:GITHUB_WORKSPACE)"",target=""c:/project"" pepperdash/sspbuilder c:\cihelpers\vsidebuild.exe -Solution ""c:\project\$($Env:SOLUTION_PATH)"" -BuildSolutionConfiguration $($ENV:BUILD_TYPE)"
      
      # Zip up the output files as needed
      - name: Zip Build Output
        shell: powershell
        run: |
          $destination = "$($Env:GITHUB_WORKSPACE)\output"
          New-Item -ItemType Directory -Force -Path ($destination)
          Get-ChildItem ($destination)
          $exclusions = "packages"
          # Trying to get any .json schema files (not currently working)
          # Gets any files with the listed extensions.
          Get-ChildItem -recurse -Path "$($Env:GITHUB_WORKSPACE)\src" -include "*.clz", "*.cpz", "*.cplz", "*.nuspec", "*.md" | ForEach-Object {
            $allowed = $true;
            # Exclude any files in submodules
            foreach ($exclude in $exclusions) {
              if ((Split-Path $_.FullName -Parent).contains("$($exclude)")) {
                $allowed = $false;
                break;
              }
            }
            if ($allowed) {
              Write-Host "allowing $($_)"
              $_;
            }
          } | Copy-Item -Destination ($destination) -Force
          Write-Host "Getting matching files..."
          # Get any files from the output folder that match the following extensions
          Get-ChildItem -Path $destination | Where-Object {($_.Extension -eq ".clz") -or ($_.Extension -eq ".cpz" -or ($_.Extension -eq ".cplz"))} | ForEach-Object { 
            # Replace the extensions with dll and xml and create an array 
            $filenames = @($($_ -replace "cpz|clz|cplz", "dll"), $($_ -replace "cpz|clz|cplz", "xml"))
            Write-Host "Filenames:"
            Write-Host $filenames
            if ($filenames.length -gt 0) {
              # Attempt to get the files and return them to the output directory
              Get-ChildItem -Recurse -Path "$($Env:GITHUB_WORKSPACE)\src" -include $filenames | Copy-Item -Destination ($destination) -Force
            }
          }
          Get-ChildItem -Path $destination\*.cplz | Rename-Item -NewName { "$($_.BaseName)-$($Env:VERSION)$($_.Extension)" } | Write-Host
          Get-ChildItem -Path $destination
        
      - name: Remove Existing Nuspec Files
        run: |
          Get-ChildItem -Path .\ -Filter *.nuspec -Recurse | Remove-Item -Force
        
      - name: Create Nuspec File
        shell: powershell
        run: |
          $year = (Get-Date).Year
          $repoFullName = "${{ github.repository }}" # Full repository name, including owner
          $repoName = $repoFullName.Split('/')[-1] # Extracting the repository name part
          $makeModelParts = $repoName -split '-'
          $makeModel = $makeModelParts[1..($makeModelParts.Length - 1)] -join ' ' # Joining all parts after the first dash
          $title = (Get-Culture).TextInfo.ToTitleCase($makeModel)
          $makeModel = $title -replace ' ', '' # Removing spaces for the ID
          $id = "PepperDash.Essentials.Plugin." + $makeModel
          echo "Repo: $repoFullName"
          echo "Repo Name: $repoName"
          echo "Make/Model: $makeModel"
          echo "Title: $title"
          echo "ID: $id"
          echo "Owner: ${{ github.repository_owner }}"
          $nuspecContent = @"
          <?xml version='1.0' encoding='utf-8'?>
          <package>
            <metadata>
              <id>$id</id>
              <version>${{ env.VERSION }}</version>
              <title>$title</title>
              <authors>PepperDash Technologies</authors>
              <owners>pepperdash</owners>
              <requireLicenseAcceptance>false</requireLicenseAcceptance>
              <license type='file'>LICENSE.md</license>
              <projectUrl>https://github.com/${{ github.repository }}</projectUrl>
              <copyright>Copyright $year</copyright>
              <description>${{ github.repository_name }} Epi</description>
              <tags>crestron 3series</tags>
              <repository type='git' url='https://github.com/${{ github.repository }}'/>
            </metadata>
            <files>
              <file src='LICENSE.md' target=''/>
              <file src='README.md' target=''/>
              <file src='./output/**' target='lib\net35'/>
              <file src='./output/**' target='lib\net47'/>
            </files>
          </package>
          "@
          echo $nuspecContent > ${{ github.workspace }}\project.nuspec
      
      - name: Get nuget File 
        shell: powershell
        run: |
          $nuspec_file = (Get-ChildItem *.nuspec -recurse).BaseName
          echo "NUSPEC_FILE=$($nuspec_file)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      
      # Pulls the nuget builder packages
      - name: Add nuget.exe
        if: ${{ !contains( env.NUSPEC_FILE, 'EssentialsPluginTemplate' ) }}
        uses: nuget/setup-nuget@v2        
      
        # Creating nuget Packages
      - name: Add Github Packages source
        if: ${{ !contains( env.NUSPEC_FILE, 'EssentialsPluginTemplate' ) }}
        run: nuget sources add -name github -source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -username Pepperdash -password ${{ secrets.GITHUB_TOKEN }}
    
      - name: Create nuget package
        if: ${{ !contains( env.NUSPEC_FILE, 'EssentialsPluginTemplate' ) }}
        run: nuget pack "./project.nuspec" -version ${{ env.VERSION }}  
      # Pushes to internal github registry
          
      - name: Publish nuget package to Github registry
        if: ${{ !contains( env.NUSPEC_FILE, 'EssentialsPluginTemplate' ) }}
        run: nuget push *.nupkg -source github -apikey ${{ secrets.GITHUB_TOKEN }} 
      # Pushes to nuget gallery
      - name: Add nuget.org API Key
        if: github.repository_owner == 'PepperDash' && github.repository_visibility == 'public' && !contains(env.NUSPEC_FILE, 'EssentialsPluginTemplate')
        run: nuget setApiKey ${{ secrets.NUGET_API_KEY }}

      - name: Publish nuget package to nuget.org
        if: github.repository_owner == 'PepperDash' && github.repository_visibility == 'public' && !contains(env.NUSPEC_FILE, 'EssentialsPluginTemplate')
        run: nuget push *.nupkg -Source https://api.nuget.org/v3/index.json
      
        # Create the release on the source repo
      - name: Get release notes
        uses: actions/download-artifact@v4
        with:
          name: change-log
      
      - name: Upload Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: output\*.*(cplz|dll|xml)
          prerelease: ${{ inputs.channel != '' }}
          tag: ${{ inputs.tag }}
          commit: ${{ github.sha }}
          bodyFile: ./CHANGELOG.md
      
