name: Update README

on:
  workflow_call:
    inputs:
      target-branch:
        description: 'The branch to commit the README.md updates to.'
        required: true
        type: string

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target-branch }}
          fetch-depth: 0

      - name: Checkout Reusable Workflow Repository
        uses: actions/checkout@v3
        with:
          repository: PepperDash/readme-automation
          path: readme-automation

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt

      - name: Run README Update Script
        run: |
          python readme-automation/.github/scripts/metadata.py

      - name: Check for Changes
        id: check_for_changes
        run: |
          if git diff --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create or Switch to 'robot-docs' Branch
        run: |
          git checkout -B robot-docs
  
      - name: Commit and Push Changes to 'robot-docs' Branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Automated README update" || echo "No changes to commit"
          git push origin robot-docs --force